### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by miketvo**
99% done. Just need to put the report PDF and paste the demo video link in.

### CODE REVIEW

**Review by LaansDole — DISMISSED** [review]
Can we add Tech Stack *puppy eyes*? Like that one section in your script

**Comment by miketvo** [comment]
> Can we add Tech Stack _puppy eyes_? Like that one section in your script

Fine, after my dinner please =)) @LaansDole

**Comment by miketvo** [comment]
> > Can we add Tech Stack _puppy eyes_? Like that one section in your script
> 
> Fine, after my dinner please =)) @LaansDole

I won't include Postman though, just gonna keep it simple like in the slides:
image

**Comment by miketvo** [comment]
Happy now @LaansDole? =))

**Review by LaansDole — APPROVED** [review]
Noice

**Review by DeathHunterX — APPROVED** [review]

**Pull request merged**
