### PR TITLE
Feature client mall components

### LINKED ISSUE #27: Frontend (client-mall): Homepage Skeleton
# Homepage 
- Product Card (Done and Responsive)
- Product List (Done and Responsive
- Sub-page for each product id: description and category (In progress)
- Filter: Search by product name and search by product category (In progress)

### PR DESCRIPTION
**Pull request by LaansDole**

### CODE REVIEW

**Review by miketvo — DISMISSED** [review]
Please fix this bug on `client-whadmin`:

image

## Error log:

```
npm run dev


  VITE v4.4.9  ready in 615 ms

  ➜  Local:   http://localhost:3002/
  ➜  Network: use --host to expose
  ➜  press h to show help
9:39:01 PM [vite] Internal server error: Failed to resolve import "./components/HomePage/HomePage" from "src\App.jsx". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/src/App.jsx:13:21
  19 |  import PrivateRouter from "./customRouter/PrivateRouter";
  20 |  import NavBar from "./components/NavBar/NavBar";
  21 |  import HomePage from "./components/HomePage/HomePage";
     |                        ^
  22 |  import LoginPage from "./pages/login";
  23 |  import RegisterPage from "./pages/register";
      at formatError (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:43993:46)
      at TransformContext.error (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:43989:19)
      at normalizeUrl (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:41801:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:41945:47
      at async Promise.all (index 7)
      at async TransformContext.transform (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:41870:13)
      at async Object.transform (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:30)
      at async loadAndTransform (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
Failed to resolve import "./components/HomePage/HomePage" from "src\App.jsx". Does the file exist?
```

**Comment by LaansDole** [comment]
> Please fix this bug on `client-whadmin`:
> 
> image
> 
> ## Error log:
> ```
> npm run dev
> 
> 
>   VITE v4.4.9  ready in 615 ms
> 
>   ➜  Local:   http://localhost:3002/
>   ➜  Network: use --host to expose
>   ➜  press h to show help
> 9:39:01 PM [vite] Internal server error: Failed to resolve import "./components/HomePage/HomePage" from "src\App.jsx". Does the file exist?
>   Plugin: vite:import-analysis
>   File: C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/src/App.jsx:13:21
>   19 |  import PrivateRouter from "./customRouter/PrivateRouter";
>   20 |  import NavBar from "./components/NavBar/NavBar";
>   21 |  import HomePage from "./components/HomePage/HomePage";
>      |                        ^
>   22 |  import LoginPage from "./pages/login";
>   23 |  import RegisterPage from "./pages/register";
>       at formatError (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:43993:46)
>       at TransformContext.error (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:43989:19)
>       at normalizeUrl (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:41801:33)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:41945:47
>       at async Promise.all (index 7)
>       at async TransformContext.transform (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:41870:13)
>       at async Object.transform (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:30)
>       at async loadAndTransform (file:///C:/Users/vomin/Projects/rmit/rmit-isys2099-group9-app/client-whadmin/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
> Failed to resolve import "./components/HomePage/HomePage" from "src\App.jsx". Does the file exist?
> ```

done

**Comment by LaansDole** [comment]
Follow the README dev and run SSR and CSR-mall at the same time to fetch the product

**Comment by miketvo** [comment]
No other bug so far, but before I approve, please provide a description of what you have implemented. I will double check if I have missed anything @LaansDole @DeathHunterX

**Review by miketvo — APPROVED** [review]
LGTM

**Review by DeathHunterX — APPROVED** [review]

**Pull request merged**
